# Dockerfile для Celery
FROM python:3.10

WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Команда для запуска Celery
CMD ["celery", "-A", "myproject", "worker", "--loglevel=info"]
